### ISSUE TITLE
Add an option to select the source media

### ISSUE THREAD

**Issue by pr2git** [Dima73/pli-openmultibootmanager#4]
I have OpenMultiboot on my Solo4K this one has an internal HDD (quite small but there are still 7 GB of free space on it) so the recording path is to a NAS, local HDD is used for timeshift.

I have another STB, this other STB also have Open Multiboot installed so the folder /open-multiboot-upload/ and /open-multiboot/ exist on its internal HDD. I have mounted the root of the second STB HDD on the Solo4K (to be able to access it easily but it is NOT mounted as replacement HDD).

Problem is that Open Multiboot decides on its own to use this mounted HDD as reference instead of my local HDD!
So I cannot install another image on my Solo4K since the Solo4K Open Multiboot reference folder is the one from the other STB. And I, of course, don't want to delete the other STB folder since I use it.

So please create a menu in Open Multiboot to be able to select the right media to use the files for Open Multiboot.

I don't understand why Open Multiboot decide to use the other STB mounted HDD on its own initiative while the folder exist on the real physical local HDD.

**Comment by Dima73** [comment]
https://github.com/Dima73/pli-openmultibootmanager/commit/656c27ba52d8aa06c4c22e676b34dbf6934aa781
